FROM alpine:3.11

LABEL Maintainer="George Zhou<alpha-coding@outlook.com >" \
  Description="PHP-PFM Docker image based on Alpine Linux." \
  Language="php7" \
  OS="Alpine Linux" \
  Service="PHP-FPM" \
  Content="php7.3 apline3.11"

# ensure www-data user exists
RUN set -eux; \
  addgroup -g 82 -S www-data; \
  adduser -u 82 -D -S -G www-data www-data
# 82 is the standard uid/gid for "www-data" in Alpine

RUN apk update && \
  apk --no-cache add \
  # official php-fpm packages
  curl \
  openssl \
  tar \
  xz \
  zlib \
  sqlite-libs \
  libsodium \
  bash \
  php \
  php-fpm \
  # wordpress required php extensions
  # graphic libraries for media
  imagemagick-dev \
  #less \
  php7-fpm \
  php7-mysqli \
  php7-json \
  php7-openssl \
  php7-curl \
  php7-zlib \
  php7-xml \
  php7-phar \
  php7-intl \
  php7-dom \
  php7-xmlreader \
  php7-xmlwriter \
  php7-exif \
  php7-fileinfo \
  php7-sodium \
  php7-gd \
  php7-imagick \
  php7-simplexml \
  php7-ctype \
  php7-mbstring \
  php7-zip \
  php7-pdo_mysql \
  # optional
  spl \
  php7-opcache \
  php7-iconv \
  # for optimization using redis-cache plugin
  php7-pecl-redis \
  && rm -rf /var/cache/apk/*

# Configure PHP-FPM
COPY docker-config/fpm-pool.conf /etc/php7/php-fpm.d/zz_docker.conf
COPY docker-config/php.ini /etc/php7/conf.d/zz_php.ini

# wordpress volume
VOLUME /var/www/html
WORKDIR /var/www/html
RUN chown -R www-data.www-data /var/www

RUN mkdir -p /usr/src \
  && chown -R www-data.www-data /usr/src

# Entrypoint 
COPY entrypoint-for-fpm.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

EXPOSE 9000

CMD ["php-fpm7"]
